In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame
data=pd.read_csv('http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv',header=None,names=['a','b','c','d'])
data2=data[1:11]
data3=data2[['a']]
def record(x):
    i=0
    df = pd.DataFrame(columns=[])
    for i in range (0,10):
        data=x.iloc[i] 
        List=data.str.split(";").tolist()  
        df=df.append(List,ignore_index=True)
        i=i+1
    return df
data4=record(data3)
def minmax(data):
    i=0
    Min=[]
    for i in range(0,11):
        df1 = pd.DataFrame(columns=[])
        df1=df1.append(data[[i]].astype('float64'))
        Min.append(df1.min())
    return Min
minmax=minmax(data4)
print(minmax)
data4

[0    6.2
dtype: float64, 1    0.22
dtype: float64, 2    0.16
dtype: float64, 3    1.5
dtype: float64, 4    0.044
dtype: float64, 5    14.0
dtype: float64, 6    97.0
dtype: float64, 7    0.9938
dtype: float64, 8    3.0
dtype: float64, 9    0.4
dtype: float64, 10    8.8
dtype: float64]

    0     1     2     3      4   5    6       7     8     9     10 11
0    7  0.27  0.36  20.7  0.045  45  170   1.001     3  0.45   8.8  6
1  6.3   0.3  0.34   1.6  0.049  14  132   0.994   3.3  0.49   9.5  6
2  8.1  0.28   0.4   6.9   0.05  30   97  0.9951  3.26  0.44  10.1  6
3  7.2  0.23  0.32   8.5  0.058  47  186  0.9956  3.19   0.4   9.9  6
4  7.2  0.23  0.32   8.5  0.058  47  186  0.9956  3.19   0.4   9.9  6
5  8.1  0.28   0.4   6.9   0.05  30   97  0.9951  3.26  0.44  10.1  6
6  6.2  0.32  0.16     7  0.045  30  136  0.9949  3.18  0.47   9.6  6
7    7  0.27  0.36  20.7  0.045  45  170   1.001     3  0.45   8.8  6
8  6.3   0.3  0.34   1.6  0.049  14  132   0.994   3.3  0.49   9.5  6
9  8.1  0.22  0.43   1.5  0.044  28  129  0.9938  3.22  0.45    11  6